### ISSUE TITLE
Problem in running your code

### ISSUE THREAD

**Issue by kushal-chakraborty** [escorciav/roi_pooling#9]
I tried running your code in my system. But I ran into some error when executing the command `python example.py` as:
`Traceback (most recent call last):
  File "example.py", line 1, in <module>
    import torch
  File "/home/pg2017/cse/17071016/.conda/envs/myenv/lib/python3.7/site-packages/torch/__init__.py", line 102, in <module>
    from torch._C import *
ImportError: /home/pg2017/cse/17071016/.conda/envs/myenv/lib/python3.7/site-packages/torch/lib/libtorch.so.1: undefined symbol: nvrtcGetProgramLogSize`

Please address this issue. Waiting for a reply.

**Comment by djongpo** [comment]
I also encountered the same problem when I installed **cupy 5.1.0** and **pytorch 1.0.1** in the environment pytorch-extensions and then tried to run the command `python example.py`. I think there is some problem with torch installation. For that, I used the command, 
`conda install pytorch==1.0.1` and I have `cuda 10.0` installed.

I see that you have listed all dependencies in `environment.yml`. When I installed all dependencies using the command, `conda env update --file environment.yml`  and then tried running the command `python example.py` it gives the error:
`Traceback (most recent call last):
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/cuda/__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 12, in <module>
    from cupy.cuda import function
  File "cupy/cuda/function.pyx", line 1, in init cupy.cuda.function
ImportError: libcuda.so.1: cannot open shared object file: No such file or directory`

`Traceback (most recent call last):
  File "example.py", line 3, in <module>
    from roi_pooling.functions.roi_pooling import roi_pooling_2d
  File "/home/pg2017/cse/17071016/roi_pooling/roi_pooling/functions/roi_pooling.py", line 29, in <module>
    from ..utils import Dtype, Stream, load_kernel
  File "/home/pg2017/cse/17071016/roi_pooling/roi_pooling/utils.py", line 17, in <module>
    import cupy
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/__init__.py", line 32, in <module>
    six.reraise(ImportError, ImportError(msg), exc_info[2])
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/six.py", line 692, in reraise
    raise value.with_traceback(tb)
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/__init__.py", line 11, in <module>
    from cupy import core  # NOQA
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/core/__init__.py", line 1, in <module>
    from cupy.core import core  # NOQA
  File "cupy/core/core.pyx", line 1, in init cupy.core.core
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/cuda/__init__.py", line 4, in <module>
    from cupy.cuda import compiler  # NOQA
  File "/home/pg2017/cse/17071016/.conda/envs/pytorch-extensions/lib/python3.7/site-packages/cupy/cuda/compiler.py", line 12, in <module>
    from cupy.cuda import function
  File "cupy/cuda/function.pyx", line 1, in init cupy.cuda.function
ImportError: CuPy is not correctly installed.`

`If you are using wheel distribution (cupy-cudaXX), make sure that the version of CuPy you installed matches with the version of CUDA on your host.`
`Also, confirm that only one CuPy package is installed:`
  `$ pip freeze` 

`original error: libcuda.so.1: cannot open shared object file: No such file or directory`

I checked with the command `pip freeze` that only one version of `cupy` exists. 

What is the problem with `libcuda.so`? As said by @kushal-chakraborty please address this problem

**Comment by escorciav** [comment]
Thanks for your interest in our work.

1. Were you able to use it in colab? Please try that first.
2. Please detail the steps used to reproduce the problem. I will try to give guidance.

Please be polite in the wait you request for help.
